set(IN_CMSSW OFF)

if(DEFINED ENV{CMSSW_VERSION})
    set(IN_CMSSW ON)

    execute_process(COMMAND scram tool tag python LIBDIR OUTPUT_VARIABLE PYTHON_LIBRARY_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND scram tool tag python LIB OUTPUT_VARIABLE PYTHON_LIBRARY OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(PYTHON_LIBRARY "${PYTHON_LIBRARY_PATH}/lib${PYTHON_LIBRARY}.so")
    execute_process(COMMAND scram tool tag python INCLUDE OUTPUT_VARIABLE PYTHON_INCLUDE_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)

    # Boost
    set(Boost_NO_SYSTEM_PATHS ON)
    execute_process(COMMAND scram tool tag boost BOOST_BASE OUTPUT_VARIABLE
        BOOST_ROOT OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
